assest/src/main/java/de/advertal/assest/models/database/Item.java
package de.advertal.assest.models.database;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import de.advertal.assest.utils.PythonFormatChecker;
import eu.bebendorf.ajorm.DatabaseField;
import eu.bebendorf.ajorm.DatabaseTable;
import eu.bebendorf.ajorm.Table;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.util.ArrayList;
import java.util.List;

@DatabaseTable("items")
@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Item {

    private static final Gson gson = new GsonBuilder().create();

    @Getter @Setter
    static Table<Item, Integer> table;

    @DatabaseField(id = true, ai = true, primary = true)
    int id;
    @DatabaseField
    Type type;
    @DatabaseField(columnName = "customer_id")
    int customerId;
    @DatabaseField(columnName = "skill_id")
    int skillId;
    @DatabaseField
    String question;
    @DatabaseField(columnName = "media_type")
    MediaType mediaType = MediaType.NONE;
    @DatabaseField
    String media = "";
    @DatabaseField(columnName = "time_limit")
    int timeLimit = 0;
    @DatabaseField
    double weight = 1;
    @DatabaseField
    boolean invert = false;
    @DatabaseField
    String answers = "";
    @DatabaseField(columnName = "correct")
    String correctAnswer = "";

    public double assertAnswer(String answer){
        if(type.likert()!=-1){
            short answerValue = Short.parseShort(answer);
            double value = (answerValue-1)*(1d/(type.likert()-1));
            if(value>0.999)
                value = 1;
            if(value<0.001)
                value = 0;
            if(!invert)
                value = 1-value;
            return value;
        }
        if(type.choice()!=-1){
            int maxAnswerCount = gson.fromJson(this.answers, String[].class).length;
            List<Integer> answers = parseIntListAnswer(answer);
            List<Integer> correctAnswers = parseIntListAnswer(correctAnswer);
            double value = 0;
            double valuePerCorrect = 1d / maxAnswerCount;
            for(int i = 1; i <= maxAnswerCount; i++){
                if(correctAnswers.contains(i) && answers.contains(i))
                    value += valuePerCorrect;
                if(!correctAnswers.contains(i) && !answers.contains(i))
                    value += valuePerCorrect;
            }
            if(type.choice()==1)
                value = value > 0.999 ? 1 : 0;
            return value;
        }
        if(type == Type.PYTHON){
            if(answer.length() < 3){
                return 0;
            }
            PythonFormatChecker check = new PythonFormatChecker(answer.split("\n"));
            List<Integer> correctAnswers = parseIntListAnswer(correctAnswer);
            double totalDif = calcDiff(check.totalLength - check.commentLength, correctAnswers.get(0));
            double commentDif = calcDiff((check.commentLength / check.totalLength) * 100, correctAnswers.get(1));
            double fnDif = 0;
            if(check.functionCount != 0){
                fnDif = calcDiff(check.functionNameLengthTotal / check.functionCount, correctAnswers.get(2));
            }
            double varDif = 0;
            if(check.variableCount != 0){
                varDif = calcDiff(check.variableNameLengthTotal / check.variableCount, correctAnswers.get(3));
            }
            double dif = ((totalDif * 2) + (commentDif * 2) + fnDif + varDif) / 6;
            return 1-dif;
        }
        return 0;
    }

    private int calcDiff(int a, int c){
        if(c == 0)
            return 1;
        int lengthDiff = Math.max(c, a) - Math.min(c, a);
        double lengthDiffPerc = lengthDiff / c;
        if(lengthDiff > 1){
            lengthDiff = 1;
        }
        return lengthDiff;
    }

    public boolean validateAnswer(String answer){
        if(type.likert()!=-1){
            if(answer.length()!=1)
                return false;
            if(!Character.isDigit(answer.charAt(0)))
                return false;
            short value = Short.parseShort(answer);
            if(value<1 || value>type.likert())
                return false;
            return true;
        }
        if(type.choice()!=-1){
            int maxAnswerCount = gson.fromJson(this.answers, String[].class).length;
            List<Integer> set = new ArrayList<>();
            String[] answers = answer.split(",");
            if(answers.length > maxAnswerCount)
                return false;
            for(String choice : answers){
                int value = parseIntAnswer(choice);
                if(value<1 || value > maxAnswerCount)
                    return false;
                if(set.contains(value))
                    return false;
                set.add(value);
            }
            if(type.choice()==1){
                if(set.size()!=1)
                    return false;
                return true;
            }else{
                return true;
            }
        }
        if(type == Type.PYTHON){
            return true;
        }
        return false;
    }

    private List<Integer> parseIntListAnswer(String answer){
        List<Integer> list = new ArrayList<>();
        for(String s : answer.split(","))
            list.add(parseIntAnswer(s));
        return list;
    }

    private int parseIntAnswer(String answer){
        try {
            return Integer.parseInt(answer);
        }catch (Exception ex){}
        return -1;
    }

    @AllArgsConstructor
    @Getter
    public enum Type {
        SINGLE_CHOICE("Single Choice"),
        MULTIPLE_CHOICE("Multiple Choice"),
        LIKERT4("Likert 4"),
        LIKERT5("Likert 5"),
        PYTHON("Python Codestyle");
        private String display;
        public int likert(){
            switch (this){
                case LIKERT4:
                    return 4;
                case LIKERT5:
                    return 5;
            }
            return -1;
        }
        public int choice(){
            switch (this){
                case SINGLE_CHOICE:
                    return 1;
                case MULTIPLE_CHOICE:
                    return 2;
            }
            return -1;
        }
    }

    public enum MediaType {
        NONE,
        IMAGE,
        AUDIO,
        VIDEO
    }

    public User getCustomer(){
        if(customerId < 1)
            return null;
        return User.getTable().queryById(customerId);
    }

    public boolean isShared(){
        return getCustomerId() < 1;
    }

    public Skill getSkill(){
        return Skill.getTable().queryById(skillId);
    }

    public void delete(){
        getTable().delete(this);
    }

}

assest/src/main/java/de/advertal/assest/models/database/Skill.java
package de.advertal.assest.models.database;

import eu.bebendorf.ajorm.DatabaseField;
import eu.bebendorf.ajorm.DatabaseTable;
import eu.bebendorf.ajorm.Table;
import lombok.AccessLevel;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.FieldDefaults;

import java.util.List;

@DatabaseTable("skills")
@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Skill {

    @Getter @Setter
    static Table<Skill, Integer> table;

    @DatabaseField(id = true, ai = true, primary = true)
    int id;
    @DatabaseField(columnName = "customer_id")
    int customerId;
    @DatabaseField(columnName = "category_id")
    int categoryId;
    @DatabaseField
    String name;
    @DatabaseField
    String description;
    @DatabaseField
    boolean soft = false;
    int amount = 0;

    public void checkAmount(){
        this.amount = getItems().size();
    }

    public User getCustomer(){
        if(customerId < 1)
            return null;
        return User.getTable().queryById(customerId);
    }

    public boolean canRead(User user){
        return customerId == 0 || customerId == user.getId();
    }

    public boolean isShared(){
        return getCustomerId() < 1;
    }

    public Category getCategory(){
        return Category.getTable().queryById(categoryId);
    }

    public List<Item> getItems(){
        return Item.getTable().queryForEq("skill_id", getId());
    }

    public String getDisplayDescription(){
        if(getDescription().length()==0)
            return "Keine Beschreibung vorhanden";
        return getDescription();
    }

    public void delete(){
        Item.getTable().queryForEq("skill_id", getId()).forEach(item -> {
            Answer.getTable().builder().where().eq("item_id", item.getId()).delete();
            Item.getTable().delete(item);
        });
        SkillResult.getTable().builder().where().eq("skill_id", getId());
        List<TestSkill> testSkills = TestSkill.getTable().queryForEq("skill_id", getId());
        for(TestSkill testSkill : testSkills){
            TestSkill.getTable().delete(testSkill);
            TestResult.getTable().builder().where().eq("test_id", testSkill.getTestId()).delete();
            for(TestRun run : TestRun.getTable().queryForEq("test_id", testSkill.getTestId())){
                if(run.getState() == ResultState.DONE){
                    run.setState(ResultState.SUBMITTED);
                    TestRun.getTable().update(run);
                }else{
                    run.setCurrent(0);
                    run.setState(ResultState.CREATED);
                    TestRun.getTable().update(run);
                }
            }
        }
        getTable().delete(this);
    }

}

assest/src/main/java/de/advertal/assest/models/database/TestRun.java
package de.advertal.assest.models.database;

import de.advertal.assest.Assest;
import de.advertal.assest.utils.RandomUtil;
import eu.bebendorf.ajorm.DatabaseField;
import eu.bebendorf.ajorm.DatabaseTable;
import eu.bebendorf.ajorm.Table;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Random;

@DatabaseTable("test_runs")
@Data
@FieldDefaults(level = AccessLevel.PRIVATE)
public class TestRun {

    @Getter @Setter
    static Table<TestRun, Integer> table;

    @DatabaseField(id = true, ai = true, primary = true)
    int id;
    @DatabaseField(columnName = "customer_id")
    int customerId;
    @DatabaseField(columnName = "test_id")
    int testId;
    @DatabaseField(columnName = "user_id")
    int userId;
    @DatabaseField
    ResultState state = ResultState.CREATED;
    @DatabaseField
    int current = 0;
    @DatabaseField
    String token;
    @DatabaseField
    String random;
    @DatabaseField(columnName = "created_at")
    Timestamp createdAt;
    @DatabaseField(columnName = "solved_at")
    Timestamp solvedAt;

    private transient Test cachedTest = null;

    public Test getTest(){
        if(cachedTest == null)
            cachedTest = Test.getTable().queryById(testId);
        return cachedTest;
    }

    public User getUser(){
        return User.getTable().queryById(userId);
    }

    public String getRandom(){
        return id +String.valueOf(testId)+ userId;
    }

    public List<SkillResult> getModuleResults(){
        return SkillResult.getTable().queryForEq("test_run_id", getId());
    }

    public TestResult getTestResult(){
        return TestResult.getTable().builder().where().eq("test_run_id", getId()).query().first();
    }

    public List<Skill> getSkills(){
        List<Skill> skills = new ArrayList<>();
        for(TestSkill relation : TestSkill.getTable().queryForEq("test_id", getTestId()))
            skills.add(relation.getSkill());
        return skills;
    }

    public List<Item> getItems(){
        List<Item> items = new ArrayList<>();
        List<Item> soft = new ArrayList<>();
        for(Skill skill : getSkills()){
            if(skill.isSoft()){
                soft.addAll(skill.getItems());
            }else{
                items.addAll(skill.getItems());
            }
        }
        soft = new ArrayList<>(RandomUtil.randomizeItems(soft, getRandom()));
        soft.addAll(items);
        return soft;
    }

    public List<Item> getItemsRandomized(){
        return getItems();
    }

    public void generateRandom(){
        char[] charSet = "abcdefghijklmnopqrstuvwxyz0123456789".toCharArray();
        Random random = new Random();
        StringBuilder sb = new StringBuilder();
        for(int i=0;i<50;i++)
            sb.append(charSet[random.nextInt(charSet.length)]);
        this.random = sb.toString();
    }

    public void generateToken(){
        char[] charSet = "abcdefghijklmnopqrstuvwxyz0123456789".toCharArray();
        Random random = new Random();
        StringBuilder sb = new StringBuilder();
        for(int i=0;i<20;i++)
            sb.append(charSet[random.nextInt(charSet.length)]);
        this.token = sb.toString();
    }

    public boolean canRead(User user){
        return user.getType().isAdmin() || customerId == user.getId();
    }

    public boolean canSolve(User user){
        return user.getType().isAdmin() || customerId == user.getId() || userId == user.getId();
    }

    public boolean canWrite(User user){
        return user.getType().isAdmin() || customerId == user.getId();
    }

    public void delete(){
        for(TestResult result : TestResult.getTable().queryForEq("test_run_id", getId()))
            TestResult.getTable().delete(result);
        for(SkillResult result : SkillResult.getTable().queryForEq("test_run_id", getId()))
            SkillResult.getTable().delete(result);
        for(Answer result : Answer.getTable().queryForEq("test_run_id", getId()))
            Answer.getTable().delete(result);
        getTable().delete(this);
    }

}

assest/src/main/java/de/advertal/assest/controller/SkillController.java
package de.advertal.assest.controller;

import com.ftpix.sparknnotation.annotations.*;
import de.advertal.assest.models.database.Category;
import de.advertal.assest.models.database.Skill;
import de.advertal.assest.models.database.User;
import de.advertal.assest.models.web.*;
import de.advertal.assest.utils.JsonTransformer;
import spark.Request;

@SparkController
public class SkillController extends Controller {

    @SparkGet(value = "/skills")
    public String getSkills(Request request){
        return VIEW(request, "skills", ME("categories", Category.getTable().queryForAll()));
    }

    @SparkPost(value = "/api/skills", transformer = JsonTransformer.class)
    public StatusResponse createSkill(Request request, @SparkBody SkillCreateRequest create){
        User user = USER(request);
        int customerId = user.getId();
        if(user.getType().isAdmin())
            customerId = 0;
        Skill skill = Skill.getTable().builder().where().eq("category_id", create.getCategoryId()).and().eq("name", create.getName()).and().c(" (").eq("customer_id", customerId).or().eq("customer_id", 0).c(")").query().first();
        if(skill!=null)
            return new StatusResponse(false, "Es existiert bereits ein Skill mit diesem Namen");
        if(create.getCategoryId()>0)
            if(Category.getTable().queryById(create.getCategoryId())==null)
                return new StatusResponse(false, "Die Kategorie existiert nicht");
        skill = new Skill();
        skill.setCustomerId(customerId);
        skill.setCategoryId(create.getCategoryId());
        skill.setDescription(create.getDescription());
        skill.setSoft(create.isSoft());
        skill.setName(create.getName());
        Skill.getTable().create(skill);
        return new StatusResponse(true, "Der Skill wurde erstellt");
    }

    @SparkDelete(value = "/api/skills/:skill", transformer = JsonTransformer.class)
    public StatusResponse deleteSkill(Request request, @SparkParam("skill") int skillId){
        User user = USER(request);
        Skill skill = Skill.getTable().queryById(skillId);
        if(skill==null)
            return new StatusResponse(false, "Der Skill wurde nicht gefunden");
        if(!user.getType().isAdmin() && skill.getCustomerId() != user.getId())
            return new StatusResponse(false, "Dafür haben Sie keine Berechtigung");
        skill.delete();
        return new StatusResponse(true, "Der Skill wurde gelöscht");
    }

    @SparkGet(value = "/api/skills/:skill", transformer = JsonTransformer.class)
    public EditSkillResponse getEditSkill(Request request, @SparkParam("skill") int skillId){
        User user = USER(request);
        Skill skill = Skill.getTable().queryById(skillId);
        if(skill==null)
            return new EditSkillResponse(false, "Der Skill wurde nicht gefunden");
        if(!user.getType().isAdmin() && skill.getCustomerId() != user.getId())
            return new EditSkillResponse(false, "Dafür haben Sie keine Berechtigung");
        return new EditSkillResponse(true, "Der Skill wurde gefunden", skill);
    }

    @SparkPost(value = "/api/skills/:skill", transformer = JsonTransformer.class)
    public StatusResponse updateSkill(Request request, @SparkParam("skill") int skillId, @SparkBody UpdateSkillRequest update){
        User user = USER(request);
        Skill skill = Skill.getTable().queryById(skillId);
        if(skill==null)
            return new StatusResponse(false, "Der Skill wurde nicht gefunden");
        if(!user.getType().isAdmin() && skill.getCustomerId() != user.getId())
            return new StatusResponse(false, "Dafür haben Sie keine Berechtigung");
        skill.setName(update.getName());
        skill.setDescription(update.getDescription());
        skill.setCategoryId(update.getCategory());
        skill.setSoft(update.isSoft());
        Skill.getTable().update(skill);
        return new StatusResponse(true, "Der Skill wurde bearbeitet");
    }

}

assest/src/main/resources/templates/evaluation-single.ftl
<#macro page_body>
    <style>
        .scale-soft {
            background: rgba(199,199,199,1);
            background: -moz-linear-gradient(left, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            background: -webkit-gradient(left top, right top, color-stop(0%, rgba(199,199,199,1)), color-stop(31%, rgba(117,116,117,1)), color-stop(47%, rgba(82,82,82,1)), color-stop(51%, rgba(82,82,82,1)), color-stop(55%, rgba(82,82,82,1)), color-stop(72%, rgba(110,110,110,1)), color-stop(100%, rgba(199,199,199,1)));
            background: -webkit-linear-gradient(left, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            background: -o-linear-gradient(left, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            background: -ms-linear-gradient(left, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            background: linear-gradient(to right, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#c7c7c7', endColorstr='#c7c7c7', GradientType=1 );
            height: 16px;
            width: 100%;
            position: relative;
        }
        .scale {
            background: rgba(61,59,61,1);
            background: -moz-linear-gradient(left, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            background: -webkit-gradient(left top, right top, color-stop(0%, rgba(61,59,61,1)), color-stop(24%, rgba(89,89,89,1)), color-stop(59%, rgba(150,150,150,1)), color-stop(100%, rgba(240,240,240,1)));
            background: -webkit-linear-gradient(left, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            background: -o-linear-gradient(left, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            background: -ms-linear-gradient(left, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            background: linear-gradient(to right, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3d3b3d', endColorstr='#f0f0f0', GradientType=1 );
            height: 16px;
            width: 100%;
            position: relative;
        }
        .scale-indicator {
            background-color: #00ace6;
            height: 40px;
            width: 5px;
            top: -28px;
            position: relative;
            border: 1px solid white;
        }
        h3 {
            margin-bottom: 25px;
        }
    </style>
    <div class="x_panel">
        <div class="x_title">
            <h2>Auswertung <small>${ run.test.name } → ${ run.user.firstName } ${ run.user.lastName }</small></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <#if testresult??>
            <h3 class="text-center">Gesamt</h3>
            <div style="width: 100%;">
                <div class="scale"></div>
                <div class="scale-indicator" style="left: ${ testresult.getValueInPercentString() }%;"></div>
            </div>
            <h4>Beschreibung</h4>
            ${ run.test.displayDescription }
            <h4>Auswertung</h4>
            ${ testresult.wording.text }
            </#if>
            <#list skillresults as skillresult>
            <hr>
            <h3 class="text-center">${ skillresult.skill.name }</h3>
            <div style="width: 100%;">
                <div class="scale<#if skillresult.skill.isSoft()>-soft</#if>"></div>
                <div class="scale-indicator" style="left: ${ skillresult.getValueInPercentString() }%;"></div>
            </div>
            <h4>Beschreibung</h4>
            ${ skillresult.skill.displayDescription }
            <h4>Auswertung</h4>
            ${ skillresult.wording.text }
            </#list>
        </div>
    </div>
</#macro>
<#include "base.ftl" />

assest/src/main/resources/templates/evaluation-test.ftl
<#macro page_body>
    <style>
        .scale-soft {
            background: rgba(199,199,199,1);
            background: -moz-linear-gradient(left, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            background: -webkit-gradient(left top, right top, color-stop(0%, rgba(199,199,199,1)), color-stop(31%, rgba(117,116,117,1)), color-stop(47%, rgba(82,82,82,1)), color-stop(51%, rgba(82,82,82,1)), color-stop(55%, rgba(82,82,82,1)), color-stop(72%, rgba(110,110,110,1)), color-stop(100%, rgba(199,199,199,1)));
            background: -webkit-linear-gradient(left, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            background: -o-linear-gradient(left, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            background: -ms-linear-gradient(left, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            background: linear-gradient(to right, rgba(199,199,199,1) 0%, rgba(117,116,117,1) 31%, rgba(82,82,82,1) 47%, rgba(82,82,82,1) 51%, rgba(82,82,82,1) 55%, rgba(110,110,110,1) 72%, rgba(199,199,199,1) 100%);
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#c7c7c7', endColorstr='#c7c7c7', GradientType=1 );
            height: 16px;
            width: 100%;
            position: relative;
        }
        .scale {
            background: rgba(61,59,61,1);
            background: -moz-linear-gradient(left, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            background: -webkit-gradient(left top, right top, color-stop(0%, rgba(61,59,61,1)), color-stop(24%, rgba(89,89,89,1)), color-stop(59%, rgba(150,150,150,1)), color-stop(100%, rgba(240,240,240,1)));
            background: -webkit-linear-gradient(left, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            background: -o-linear-gradient(left, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            background: -ms-linear-gradient(left, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            background: linear-gradient(to right, rgba(61,59,61,1) 0%, rgba(89,89,89,1) 24%, rgba(150,150,150,1) 59%, rgba(240,240,240,1) 100%);
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3d3b3d', endColorstr='#f0f0f0', GradientType=1 );
            height: 16px;
            width: 100%;
            position: relative;
        }
        .scale-indicator {
            background-color: #00ace6;
            height: 40px;
            width: 5px;
            top: -28px;
            position: relative;
            border: 1px solid white;
        }
        h3 {
            margin-bottom: 25px;
        }
    </style>
    <div class="x_panel">
        <div class="x_title">
            <h2>Auswertung <small>${ test.name }</small></h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <#if testValue??>
            <h3 class="text-center">Gesamt</h3>
            <div style="width: 100%;">
                <div class="scale"></div>
                <div class="scale-indicator" style="left: ${ testValue }%;"></div>
            </div>
            <h4>Beschreibung</h4>
            ${ test.displayDescription }
            <h4>Auswertung</h4>
            ${ testwording.text }
            </#if>
            <#list skillresults as skillresult>
            <hr>
            <h3 class="text-center">${ skillresult.skill.name }</h3>
            <div style="width: 100%;">
                <div class="scale<#if skillresult.skill.isSoft()>-soft</#if>"></div>
                <div class="scale-indicator" style="left: ${ skillresult.getValueInPercentString() }%;"></div>
            </div>
            <h4>Beschreibung</h4>
            ${ skillresult.skill.displayDescription }
            <h4>Auswertung</h4>
            Hier wird später das Wording für den erreichten Wert stehen.
            </#list>
        </div>
    </div>
</#macro>
<#include "base.ftl" />